services:
  postgres-chillchair:
    image: postgres:12
    environment:
      - POSTGRES_USER=chillchair
      - POSTGRES_PASSWORD=chillchair
      - POSTGRES_DB=chillchair
    ports:
      - "35432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  django-chillchair:
    image: chillchair
    restart: unless-stopped
    build:
      context: .
    command: django
    volumes:
      - .:/code
      - dmedia:/media
      - dstatic:/static
    ports:
      - "39000:8000"
    depends_on:
      - postgres-chillchair
    environment:
      - CONTAINER_ENVIRONMENT=local
      - DJANGO_SETTINGS_MODULE=config.settings
      - DATABASE_URL=psql://chillchair:chillchair@postgres-chillchair:5432/chillchair

networks:
  default:
    name: chillchair_default
#    external:
#      true

volumes:
  pgdata:
  rdata:
  mdata:
  dmedia:
  dstatic: