# Generated by Django 4.2.17 on 2025-04-08 11:19

import app.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rating_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="chair",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=app.core.models.Chair._upload_path
            ),
        ),
    ]
