# Generated by Django 4.2.17 on 2025-04-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_chair_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="chair",
        ),
        migrations.AddField(
            model_name="rating",
            name="source",
            field=models.CharField(
                choices=[("Chair", "Chair")],
                db_index=True,
                default="chair",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rating",
            name="source_id",
            field=models.BigIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
