# Generated by Django 4.2.17 on 2025-05-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chair_city_chair_latitude_chair_longitude_chair_road'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=10),
        ),
    ]
